name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:

    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        # All supported PHP versions https://www.php.net/supported-versions.php
        php: [ '7.4', '8.0', '8.1', '8.2' ]

    runs-on: ${{ matrix.os }}

    name: PHP ${{ matrix.php }} on ${{ matrix.os }} with ${{ matrix.db }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{matrix.php}}
        extensions: fileinfo, json, curl

    - name: Install
      run: |
        composer install

    - name: Test
      run: |
        composer test
